spring:
  datasource:
    url: jdbc:mysql://localhost:8080/blog?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    password: 123
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.gjb: info
  file: log/blog-pro.log

server:
  port: 8081
